import { Feather } from '@expo/vector-icons';
import React, { useMemo, useState } from 'react';
import {
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { FadeInView } from '../../components/common/FadeInView';

import AlertCard from '../../components/alerts/AlertCard';
import Skeleton from '../../components/common/Skeleton';
import { ErrorBoundary } from '../../components/common/ErrorBoundary';

import { getAlerts } from '../../services/api';
import { useThemeColor } from '../../hooks/useThemeColor';

export default function AlertsPage() {
  const theme = useThemeColor();
  const [filter, setFilter] = useState<'ALL' | 'CRITICAL' | 'HIGH' | 'MEDIUM'>('ALL');

  const { data: alerts, isLoading } = useQuery({ queryKey: ['alerts'], queryFn: getAlerts });

  const filtered = useMemo(() => {
    if (!alerts) return [];
    return filter === 'ALL' ? alerts : alerts.filter((a) => a.severity === filter);
  }, [alerts, filter]);

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'CRITICAL': return theme.danger;
      case 'HIGH': return theme.warning;
      case 'MEDIUM': return '#eab308';
      default: return theme.border;
    }
  };

  return (
    <ScrollView style={[styles.container, { backgroundColor: theme.background }]} showsVerticalScrollIndicator={false}>

      {/* Top Bar */}
      <View style={[styles.topBar, { backgroundColor: theme.surface, borderBottomColor: theme.border }]}>
        <View style={{ flex: 1 }}>
          <Text style={[styles.pageTitle, { color: theme.text }]}>System Tamper Alerts</Text>
          <Text style={[styles.pageSub, { color: theme.textSecondary }]}>
            Anomalies auto-detected by XGBoost + SHAP explainability engine
          </Text>
        </View>
        <ErrorBoundary>
          <View style={styles.summaryPills}>
            <View style={[styles.pill, { backgroundColor: theme.dangerBg, borderColor: theme.dangerBorder }]}>
              <Feather name="alert-octagon" size={10} color={theme.danger} />
              <Text style={[styles.pillText, { color: theme.danger }]}>
                {isLoading ? '...' : alerts?.filter(a => a.severity === 'CRITICAL').length} CRITICAL
              </Text>
            </View>
            <View style={[styles.pill, { backgroundColor: theme.warningBg, borderColor: theme.warningBorder }]}>
              <Text style={[styles.pillText, { color: theme.warning }]}>
                {isLoading ? '...' : alerts?.filter(a => a.severity === 'HIGH').length} HIGH
              </Text>
            </View>
            <View style={[styles.pill, { backgroundColor: '#fefce8', borderColor: '#fef08a' }]}>
              <Text style={[styles.pillText, { color: '#854d0e' }]}>
                {isLoading ? '...' : alerts?.filter(a => a.severity === 'MEDIUM').length} MEDIUM
              </Text>
            </View>
          </View>
        </ErrorBoundary>
      </View>

      <View style={styles.content}>

        {/* Info Box */}
        <FadeInView delay={100} translateY={-10} style={[styles.infoBox, { backgroundColor: theme.primaryBg, borderColor: theme.primaryBorder }]}>
          <Feather name="cpu" size={14} color={theme.primary} />
          <Text style={[styles.infoText, { color: theme.primary }]}>
            All alerts are generated by the ForensiAir Engine using 15 forensic fingerprint vectors
            including zero-variance detection, inspection-timed dip analysis, and cross-parameter
            decoupling. Each alert includes a SHAP confidence score.
          </Text>
        </FadeInView>

        {/* Filter Tabs */}
        <View style={styles.filterRow}>
          {(['ALL', 'CRITICAL', 'HIGH', 'MEDIUM'] as const).map((f) => {
            const isActive = filter === f;
            return (
              <Pressable
                key={f}
                onPress={() => setFilter(f)}
                style={[
                  styles.filterTab, 
                  { backgroundColor: isActive ? theme.text : theme.surface, borderColor: isActive ? theme.text : theme.border }
                ]}
                accessibilityRole="button"
                accessibilityLabel={`Filter by ${f}`}
                accessibilityState={{ selected: isActive }}
              >
                {f !== 'ALL' && (
                  <View style={[styles.filterDot, { backgroundColor: getSeverityColor(f) }]} />
                )}
                <Text style={[styles.filterText, { color: isActive ? theme.surface : theme.textSecondary }]}>{f}</Text>
              </Pressable>
            );
          })}
          <View style={{ flex: 1 }} />
          <Text style={[styles.alertCount, { color: theme.textSecondary }]}>
            {isLoading ? 'Loading...' : `${filtered.length} alert${filtered.length !== 1 ? 's' : ''}`}
          </Text>
        </View>

        {/* Alert Cards */}
        <ErrorBoundary>
          <View style={{ gap: 14 }}>
            {isLoading ? (
              Array.from({ length: 4 }).map((_, i) => (
                <Skeleton key={i} height={120} borderRadius={14} />
              ))
            ) : (
              filtered.map((alert, i) => (
                <FadeInView key={alert.id} delay={i * 100} translateY={15}>
                  <AlertCard alert={alert} />
                </FadeInView>
              ))
            )}
          </View>
        </ErrorBoundary>

        {/* 30-Day Alert Timeline */}
        <FadeInView delay={400} style={[styles.timelineCard, { backgroundColor: theme.surface, borderColor: theme.border }]}>
          <Text style={[styles.cardTitle, { color: theme.text }]}>30-Day Alert Timeline</Text>
          <Text style={[styles.cardSub, { color: theme.textSecondary }]}>
            Daily count of AI-flagged anomalies across all MIDC clusters
          </Text>
          <View style={styles.timelineBars}>
            {[2,1,4,3,0,1,5,2,3,6,2,1,3,4,0,2,1,3,5,2,4,1,3,2,4,3,5,4,3,5].map((v, i) => (
              <View key={i} style={styles.timelineBarCol}>
                <View
                  style={[
                    styles.timelineBar,
                    {
                      height: v * 8 + 4,
                      backgroundColor: v >= 5 ? theme.danger : v >= 3 ? theme.warning : theme.primary,
                    },
                  ]}
                />
              </View>
            ))}
          </View>
          <View style={styles.timelineLabels}>
            <Text style={[styles.timelineLabelText, { color: theme.textSecondary }]}>30 days ago</Text>
            <Text style={[styles.timelineLabelText, { color: theme.textSecondary }]}>Today</Text>
          </View>
        </FadeInView>

      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  topBar: {
    padding: 20,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 12,
  },
  pageTitle: { fontSize: 20, fontWeight: '900', marginBottom: 4 },
  pageSub: { fontSize: 12, fontWeight: '500' },
  summaryPills: { flexDirection: 'row', gap: 6 },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 6,
    borderWidth: 1,
  },
  pillText: { fontSize: 10, fontWeight: '800' },
  content: { padding: 20, gap: 14 },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    borderWidth: 1,
    borderRadius: 10,
    padding: 14,
  },
  infoText: { fontSize: 12, lineHeight: 20, flex: 1 },
  filterRow: { flexDirection: 'row', alignItems: 'center', gap: 4, flexWrap: 'wrap' },
  filterTab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
  },
  filterDot: { width: 6, height: 6, borderRadius: 3 },
  filterText: { fontSize: 12, fontWeight: '600' },
  alertCount: { fontSize: 12, fontWeight: '500' },
  timelineCard: {
    borderRadius: 14,
    borderWidth: 1,
    padding: 20,
    marginTop: 4,
  },
  cardTitle: { fontSize: 14, fontWeight: '800', marginBottom: 4 },
  cardSub: { fontSize: 11, marginBottom: 16 },
  timelineBars: { flexDirection: 'row', alignItems: 'flex-end', gap: 3, height: 52 },
  timelineBarCol: { flex: 1, alignItems: 'center', justifyContent: 'flex-end' },
  timelineBar: { width: '100%', minHeight: 4, borderRadius: 2 },
  timelineLabels: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 },
  timelineLabelText: { fontSize: 10 },
});