import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

const COMPLIANCE_DATA = [
  { factory: 'Deepak Fertilizers', cto: 'MPCB/CTO/TLJ/2024/0041', validity: '31-Mar-2026', status: 'SHOW CAUSE', risk: 'CRITICAL', violations: 7, lastInsp: '18-Jul-2025' },
  { factory: 'Tata Power Unit 3', cto: 'MPCB/CTO/TRM/2023/0028', validity: '30-Jun-2026', status: 'NOTICE ISSUED', risk: 'HIGH', violations: 4, lastInsp: '02-Jul-2025' },
  { factory: 'Reliance Industries', cto: 'MPCB/CTO/NMB/2024/0055', validity: '31-Dec-2025', status: 'UNDER REVIEW', risk: 'MEDIUM', violations: 2, lastInsp: '15-Jun-2025' },
  { factory: 'Hindalco Ltd.', cto: 'MPCB/CTO/TLJ/2023/0019', validity: '28-Feb-2026', status: 'COMPLIANT', risk: 'MEDIUM', violations: 1, lastInsp: '10-Jun-2025' },
  { factory: 'JSW Steel Pvt.', cto: 'MPCB/CTO/VVR/2024/0037', validity: '30-Sep-2026', status: 'COMPLIANT', risk: 'LOW', violations: 0, lastInsp: '01-Jun-2025' },
];

const STATUS_STYLES: Record<string, { bg: string; border: string; text: string }> = {
  'SHOW CAUSE': { bg: '#fef2f2', border: '#fecaca', text: '#b91c1c' },
  'NOTICE ISSUED': { bg: '#fff7ed', border: '#fed7aa', text: '#c2410c' },
  'UNDER REVIEW': { bg: '#fefce8', border: '#fef08a', text: '#854d0e' },
  'COMPLIANT': { bg: '#f0fdf4', border: '#bbf7d0', text: '#15803d' },
};

export default function ReportScreen() {
  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} style={styles.backBtn}>
          <Feather name="arrow-left" size={16} color="#2563eb" />
          <Text style={styles.backText}>Back</Text>
        </Pressable>
        <Text style={styles.pageTitle}>Cluster Compliance Report</Text>
        <Text style={styles.pageSub}>Taloja MIDC · As of 20 July 2025 · Auto-generated by MPCB AI-Audit</Text>

        <View style={styles.kpiRow}>
          {[
            { label: 'Total Industries', value: '12', icon: 'home', color: '#2563eb' },
            { label: 'Fully Compliant', value: '4', icon: 'check-circle', color: '#10b981' },
            { label: 'Active Violations', value: '318', icon: 'alert-triangle', color: '#ef4444' },
            { label: 'Notices Issued', value: '7', icon: 'file-text', color: '#f97316' },
          ].map((k) => (
            <View key={k.label} style={styles.kpiCard}>
              <View style={[styles.kpiIcon, { backgroundColor: k.color + '20' }]}>
                <Feather name={k.icon as any} size={16} color={k.color} />
              </View>
              <Text style={[styles.kpiValue, { color: k.color }]}>{k.value}</Text>
              <Text style={styles.kpiLabel}>{k.label}</Text>
            </View>
          ))}
        </View>
      </View>

      <View style={styles.content}>
        <View style={styles.card}>
          <Text style={styles.cardTitle}>CTO / CTE Compliance Register</Text>
          {COMPLIANCE_DATA.map((row, i) => (
            <View key={i} style={styles.complianceRow}>
              <View style={styles.complianceMain}>
                <Text style={styles.complianceFactory}>{row.factory}</Text>
                <Text style={styles.complianceCTO}>{row.cto}</Text>
                <View style={styles.complianceMeta}>
                  <Text style={styles.complianceMetaText}>Valid till: {row.validity}</Text>
                  <Text style={styles.dot}>·</Text>
                  <Text style={styles.complianceMetaText}>Last Insp: {row.lastInsp}</Text>
                  <Text style={styles.dot}>·</Text>
                  <Text style={styles.complianceMetaText}>{row.violations} violation{row.violations !== 1 ? 's' : ''}</Text>
                </View>
              </View>
              <View style={[
                styles.statusChip,
                { backgroundColor: STATUS_STYLES[row.status].bg, borderColor: STATUS_STYLES[row.status].border }
              ]}>
                <Text style={[styles.statusText, { color: STATUS_STYLES[row.status].text }]}>{row.status}</Text>
              </View>
            </View>
          ))}
        </View>

        <View style={styles.card}>
          <Text style={styles.cardTitle}>Enforcement Actions Summary</Text>
          {[
            { action: 'Legal Notices Issued', count: 3, icon: 'mail', color: '#ef4444' },
            { action: 'Show Cause Notices', count: 1, icon: 'alert-circle', color: '#f97316' },
            { action: 'Temporary Closures', count: 0, icon: 'x-circle', color: '#64748b' },
            { action: 'Compliance Achieved (after notice)', count: 2, icon: 'check-circle', color: '#10b981' },
          ].map((a, i) => (
            <View key={i} style={styles.enforcementRow}>
              <View style={[styles.enforcementIcon, { backgroundColor: a.color + '18' }]}>
                <Feather name={a.icon as any} size={14} color={a.color} />
              </View>
              <Text style={styles.enforcementText}>{a.action}</Text>
              <Text style={[styles.enforcementCount, { color: a.color }]}>{a.count}</Text>
            </View>
          ))}
        </View>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f1f5f9' },
  header: { backgroundColor: '#0b1120', padding: 24 },
  backBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 16 },
  backText: { color: '#2563eb', fontSize: 13, fontWeight: '600' },
  pageTitle: { fontSize: 22, fontWeight: '900', color: '#fff', marginBottom: 4 },
  pageSub: { fontSize: 12, color: '#475569', marginBottom: 24 },
  kpiRow: { flexDirection: 'row', gap: 10, flexWrap: 'wrap' },
  kpiCard: {
    flex: 1, minWidth: 120, backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1, borderColor: '#1e293b', borderRadius: 12, padding: 14, alignItems: 'center', gap: 4,
  },
  kpiIcon: { width: 36, height: 36, borderRadius: 10, justifyContent: 'center', alignItems: 'center', marginBottom: 4 },
  kpiValue: { fontSize: 24, fontWeight: '900' },
  kpiLabel: { fontSize: 10, color: '#475569', textAlign: 'center', fontWeight: '500' },
  content: { padding: 20, gap: 16 },
  card: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#e2e8f0', padding: 20 },
  cardTitle: { fontSize: 15, fontWeight: '800', color: '#0f172a', marginBottom: 16 },
  complianceRow: {
    flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between',
    paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#f1f5f9', gap: 10,
  },
  complianceMain: { flex: 1 },
  complianceFactory: { fontSize: 14, fontWeight: '700', color: '#0f172a', marginBottom: 3 },
  complianceCTO: { fontSize: 10, color: '#94a3b8', fontFamily: 'monospace', marginBottom: 4 },
  complianceMeta: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 4 },
  complianceMetaText: { fontSize: 10, color: '#64748b' },
  dot: { fontSize: 10, color: '#cbd5e1' },
  statusChip: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 20, borderWidth: 1 },
  statusText: { fontSize: 10, fontWeight: '800' },
  enforcementRow: {
    flexDirection: 'row', alignItems: 'center', gap: 12,
    paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#f8fafc',
  },
  enforcementIcon: { width: 34, height: 34, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  enforcementText: { flex: 1, fontSize: 13, color: '#475569', fontWeight: '500' },
  enforcementCount: { fontSize: 20, fontWeight: '900' },
});